import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Camera, Eye, EyeOff, KeyRound, Mail, Save, ShieldCheck, UserRound, X } from "lucide-react";
import { apiFetch } from "../../../services/apiFetch";

function strongPasswordRules(value) { const s = String(value || ""); return { len: s.length >= 8, upper: /[A-Z]/.test(s), lower: /[a-z]/.test(s), num: /[0-9]/.test(s), sym: /[^A-Za-z0-9]/.test(s) }; }
function allRulesOk(rules) { return rules.len && rules.upper && rules.lower && rules.num && rules.sym; }
function roleLabel(role) { return ({ admin: "Administrador", fisioterapeuta: "Fisioterapeuta", terapeuta: "Terapeuta", nutriologo: "Nutriólogo", dentista: "Dentista", recepcion: "Recepción", practicante: "Practicante" })[role] || role || "Usuario"; }
const inputClass = "h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm text-slate-900 outline-none transition focus:border-blue-400 focus:bg-white focus:ring-4 focus:ring-blue-100";
function PasswordInput({ value, onChange, show, onToggle, placeholder }) { return <div className="relative"><input value={value} onChange={e => onChange(e.target.value)} type={show ? "text" : "password"} placeholder={placeholder} className={`${inputClass} pr-11`} autoComplete="new-password" /><button type="button" onClick={onToggle} className="absolute right-1.5 top-1.5 grid h-8 w-8 place-items-center rounded-lg text-slate-500 hover:bg-white">{show ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div>; }
function Rule({ ok, children }) { return <div className={`flex items-center gap-2 text-[11px] font-semibold ${ok ? "text-emerald-700" : "text-slate-500"}`}><span className={`h-2 w-2 rounded-full ${ok ? "bg-emerald-500" : "bg-slate-300"}`} />{children}</div>; }
function Field({ label, icon: Icon, children }) { return <label><span className="mb-1.5 flex items-center gap-1.5 text-[11px] font-bold text-slate-600">{Icon && <Icon className="h-3.5 w-3.5" />}{label}</span>{children}</label>; }

export function UserProfileView({ me, onUpdated, onShowInfo }) {
    const [form, setForm] = useState({ username: "", first_name: "", last_name: "", email: "" }); const [photo, setPhoto] = useState(null); const [preview, setPreview] = useState(""); const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [showCurrent, setShowCurrent] = useState(false); const [showNew, setShowNew] = useState(false); const [loading, setLoading] = useState(false); const rules = useMemo(() => strongPasswordRules(newPassword), [newPassword]); const canSavePassword = !newPassword || (Boolean(currentPassword) && allRulesOk(rules));
    useEffect(() => { setForm({ username: me?.username || "", first_name: me?.first_name || "", last_name: me?.last_name || "", email: me?.email || "" }); setPreview(me?.foto_url || ""); setPhoto(null); }, [me]);
    useEffect(() => { if (!photo) return; const url = URL.createObjectURL(photo); setPreview(url); return () => URL.revokeObjectURL(url); }, [photo]);
    const set = (key, value) => setForm(prev => ({ ...prev, [key]: value })); const initial = String(form.first_name || form.username || "U").trim()[0]?.toUpperCase() || "U";
    async function save() { if (!form.username.trim()) return onShowInfo?.("El usuario es requerido.", "Validación"); if (!form.email.trim()) return onShowInfo?.("El correo es requerido.", "Validación"); if (newPassword && !currentPassword) return onShowInfo?.("Escribe tu contraseña actual para cambiarla.", "Validación"); if (newPassword && !allRulesOk(rules)) return onShowInfo?.("La nueva contraseña no cumple los requisitos de seguridad.", "Validación"); setLoading(true); try { const fd = new FormData(); Object.entries(form).forEach(([key, value]) => fd.append(key, String(value || "").trim())); if (photo) fd.append("foto", photo); if (newPassword) { fd.append("current_password", currentPassword); fd.append("new_password", newPassword); } const response = await apiFetch("/api/me/update/", { method: "PATCH", body: fd }); const data = await response.json().catch(() => null); if (!response.ok) return onShowInfo?.(data?.detail || "No se pudo guardar el perfil.", "Error"); setCurrentPassword(""); setNewPassword(""); setShowCurrent(false); setShowNew(false); setPhoto(null); onUpdated?.(data); onShowInfo?.("Perfil actualizado correctamente.", "Listo"); } catch { onShowInfo?.("No se pudo conectar con el servidor.", "Error"); } finally { setLoading(false); } }
    return <div className="min-h-full bg-[#f6f8fc] p-4 sm:p-6"><div className="mx-auto grid max-w-6xl gap-4 lg:grid-cols-[320px_minmax(0,1fr)]"><aside className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="bg-gradient-to-br from-[#071d44] via-[#0a2f68] to-[#1746D1] p-6 text-white"><div className="relative mx-auto h-28 w-28"><div className="grid h-full w-full place-items-center overflow-hidden rounded-[30px] border-4 border-white/25 bg-white/10 text-4xl font-black shadow-2xl">{preview ? <img src={preview} alt="Perfil" className="h-full w-full object-cover" /> : initial}</div><label className="absolute -bottom-2 -right-2 grid h-10 w-10 cursor-pointer place-items-center rounded-2xl border-2 border-white bg-blue-500 text-white shadow-lg hover:bg-blue-400"><Camera className="h-4 w-4" /><input type="file" accept="image/*" className="hidden" onChange={e => setPhoto(e.target.files?.[0] || null)} /></label></div><h2 className="mt-5 text-center text-xl font-black">{`${form.first_name} ${form.last_name}`.trim() || form.username}</h2><p className="mt-1 text-center text-xs text-blue-100/70">@{form.username}</p><div className="mt-4 flex justify-center"><span className="inline-flex items-center gap-1.5 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold"><ShieldCheck className="h-3.5 w-3.5" />{roleLabel(me?.rol)}</span></div></div><div className="space-y-3 p-5"><div className="rounded-2xl border border-slate-100 bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Correo de acceso</p><p className="mt-1 truncate text-xs font-bold text-slate-700">{form.email || "Sin correo"}</p></div><div className="rounded-2xl border border-slate-100 bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Interfaces asignadas</p><div className="mt-2 flex flex-wrap gap-1.5">{(me?.interfaces || []).map(item => <span key={item} className="rounded-lg bg-white px-2 py-1 text-[9px] font-bold text-slate-600 shadow-sm">{item}</span>)}</div></div>{photo && <button type="button" onClick={() => { setPhoto(null); setPreview(me?.foto_url || ""); }} className="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-[11px] font-bold text-slate-600 hover:bg-slate-50"><X className="h-3.5 w-3.5" />Descartar foto nueva</button>}</div></aside>
        <main className="space-y-4"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5"><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-blue-600"><UserRound className="h-4 w-4" />Información personal</span><h3 className="mt-2 text-lg font-black text-slate-950">Datos de tu cuenta</h3><p className="mt-1 text-xs text-slate-500">Actualiza la información que identifica tu sesión y perfil.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Usuario" icon={UserRound}><input value={form.username} onChange={e => set("username", e.target.value)} className={inputClass} /></Field><Field label="Correo" icon={Mail}><input type="email" value={form.email} onChange={e => set("email", e.target.value)} className={inputClass} /></Field><Field label="Nombre"><input value={form.first_name} onChange={e => set("first_name", e.target.value)} className={inputClass} /></Field><Field label="Apellidos"><input value={form.last_name} onChange={e => set("last_name", e.target.value)} className={inputClass} /></Field></div></section>
            <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5"><span className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-[.14em] text-violet-600"><KeyRound className="h-4 w-4" />Seguridad</span><h3 className="mt-2 text-lg font-black text-slate-950">Cambiar contraseña</h3><p className="mt-1 text-xs text-slate-500">Déjala vacía si solo quieres actualizar tus datos.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Contraseña actual"><PasswordInput value={currentPassword} onChange={setCurrentPassword} show={showCurrent} onToggle={() => setShowCurrent(v => !v)} placeholder="••••••••" /></Field><Field label="Nueva contraseña"><PasswordInput value={newPassword} onChange={setNewPassword} show={showNew} onToggle={() => setShowNew(v => !v)} placeholder="••••••••" /></Field></div><div className="mt-4 grid gap-2 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><Rule ok={rules.len}>Mínimo 8 caracteres</Rule><Rule ok={rules.upper}>Una mayúscula</Rule><Rule ok={rules.lower}>Una minúscula</Rule><Rule ok={rules.num}>Un número</Rule><Rule ok={rules.sym}>Un símbolo</Rule></div></section>
            <div className="flex justify-end"><button type="button" onClick={save} disabled={loading || !canSavePassword} className="inline-flex h-11 items-center gap-2 rounded-xl bg-[#0a2f68] px-5 text-xs font-black text-white shadow-lg shadow-blue-900/15 hover:bg-[#123d7c] disabled:opacity-50"><Save className="h-4 w-4" />{loading ? "Guardando..." : "Guardar cambios"}</button></div></main></div></div>;
}
